eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8575/eureka
server:
  port: 8888
spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8595