eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8575/eureka
server:
  port: 8888
spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8595
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'