eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        service-Url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    instance:
        hostname: localhost
server:
    port: 8575
spring:
    application:
        name: eureka-server-lb
    config:
        import: optional:configserver:http://localhost:8595
